package dev.adamhodgkinson.game.navigation;

import com.badlogic.gdx.math.GridPoint2;
import dev.adamhodgkinson.game.Enemy;

/**
 * A class generated by PathFinder to facilitate the multi-threaded pathfinding requests of the entities
 */
public class PathFindTask implements Runnable {
    private PathFinder pathFinder;
    Enemy e;
    GridPoint2 start;
    GridPoint2 end;

    public PathFindTask(Enemy e, GridPoint2 start, GridPoint2 end, PathFinder pf) {
        this.start = start;
        this.end = end;
        this.e = e;
        pathFinder = pf;
    }

    public void run() {
        try {
            Vertex[] path = pathFinder.search(start, end);
            e.receivePath(path);
        } catch (Exception err) {
            System.out.println("failed finding path");
            System.out.println(err.getMessage());
            e.receivePath(null);
        }
    }
}
